# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui\interface_rem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from time import sleep

from PyQt5 import QtCore, QtGui, QtWidgets

import os, popup_progresso

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMessageBox, QListWidgetItem

from src import nosso_back_end, handler_historico

#foi?

def formatar_resultado(dict_resultado):
    s = ""
    for key in dict_resultado:
        s += "{}: {}\n\n".format(key, dict_resultado[key])
    return s


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 609)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        Form.setFont(font)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 800, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.tela_inicial = QtWidgets.QWidget()
        self.tela_inicial.setObjectName("tela_inicial")
        self.tela_inicial_label_1 = QtWidgets.QLabel(self.tela_inicial)
        self.tela_inicial_label_1.setGeometry(QtCore.QRect(0, 180, 800, 50))
        self.tela_inicial_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_inicial_label_1.setObjectName("tela_inicial_label_1")
        self.tela_inicial_label_2 = QtWidgets.QLabel(self.tela_inicial)
        self.tela_inicial_label_2.setGeometry(QtCore.QRect(0, 400, 800, 101))
        self.tela_inicial_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_inicial_label_2.setWordWrap(True)
        self.tela_inicial_label_2.setObjectName("tela_inicial_label_2")
        self.tela_inicial_splitter = QtWidgets.QSplitter(self.tela_inicial)
        self.tela_inicial_splitter.setGeometry(QtCore.QRect(100, 300, 600, 50))
        self.tela_inicial_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.tela_inicial_splitter.setObjectName("tela_inicial_splitter")
        self.tela_inicial_botao_reconhecer = QtWidgets.QPushButton(self.tela_inicial_splitter)
        self.tela_inicial_botao_reconhecer.setObjectName("tela_inicial_botao_reconhecer")
        self.tela_inicial_botao_historico = QtWidgets.QPushButton(self.tela_inicial_splitter)
        self.tela_inicial_botao_historico.setObjectName("tela_inicial_botao_historico")
        self.tela_inicial_botao_config = QtWidgets.QPushButton(self.tela_inicial_splitter)
        self.tela_inicial_botao_config.setObjectName("tela_inicial_botao_config")
        self.tela_inicial_botao_sobre = QtWidgets.QPushButton(self.tela_inicial_splitter)
        self.tela_inicial_botao_sobre.setObjectName("tela_inicial_botao_sobre")
        self.stackedWidget.addWidget(self.tela_inicial)
        self.tela_sobre = QtWidgets.QWidget()
        self.tela_sobre.setObjectName("tela_sobre")
        self.tela_sobre_textBrowser = QtWidgets.QTextBrowser(self.tela_sobre)
        self.tela_sobre_textBrowser.setGeometry(QtCore.QRect(10, 70, 781, 531))
        self.tela_sobre_textBrowser.setObjectName("tela_sobre_textBrowser")
        self.tela_sobre_label_1 = QtWidgets.QLabel(self.tela_sobre)
        self.tela_sobre_label_1.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.tela_sobre_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_sobre_label_1.setObjectName("tela_sobre_label_1")
        self.tela_sobre_botao_voltar = QtWidgets.QPushButton(self.tela_sobre)
        self.tela_sobre_botao_voltar.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.tela_sobre_botao_voltar.setObjectName("tela_sobre_botao_voltar")
        self.stackedWidget.addWidget(self.tela_sobre)
        self.tela_reco = QtWidgets.QWidget()
        self.tela_reco.setObjectName("tela_reco")
        self.tela_reco_botao_voltar = QtWidgets.QPushButton(self.tela_reco)
        self.tela_reco_botao_voltar.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.tela_reco_botao_voltar.setObjectName("tela_reco_botao_voltar")
        self.tela_reco_label_1 = QtWidgets.QLabel(self.tela_reco)
        self.tela_reco_label_1.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.tela_reco_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_reco_label_1.setObjectName("tela_reco_label_1")
        self.tela_reco_botao_add_amostra = QtWidgets.QPushButton(self.tela_reco)
        self.tela_reco_botao_add_amostra.setGeometry(QtCore.QRect(10, 250, 191, 41))
        self.tela_reco_botao_add_amostra.setObjectName("tela_reco_botao_add_amostra")
        self.tela_reco_listWidget = QtWidgets.QListWidget(self.tela_reco)
        self.tela_reco_listWidget.setGeometry(QtCore.QRect(10, 300, 781, 251))
        self.tela_reco_listWidget.setAlternatingRowColors(True)
        self.tela_reco_listWidget.setObjectName("tela_reco_listWidget")
        self.tela_reco_botao_reconhecer = QtWidgets.QPushButton(self.tela_reco)
        self.tela_reco_botao_reconhecer.setGeometry(QtCore.QRect(640, 560, 151, 41))
        self.tela_reco_botao_reconhecer.setObjectName("tela_reco_botao_reconhecer")
        self.tela_reco_label_2 = QtWidgets.QLabel(self.tela_reco)
        self.tela_reco_label_2.setGeometry(QtCore.QRect(20, 70, 761, 171))
        self.tela_reco_label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tela_reco_label_2.setWordWrap(True)
        self.tela_reco_label_2.setObjectName("tela_reco_label_2")
        self.tela_reco_label_1.raise_()
        self.tela_reco_botao_voltar.raise_()
        self.tela_reco_botao_add_amostra.raise_()
        self.tela_reco_listWidget.raise_()
        self.tela_reco_botao_reconhecer.raise_()
        self.tela_reco_label_2.raise_()
        self.stackedWidget.addWidget(self.tela_reco)
        self.tela_resultado = QtWidgets.QWidget()
        self.tela_resultado.setObjectName("tela_resultado")
        self.tela_resultado_label_1 = QtWidgets.QLabel(self.tela_resultado)
        self.tela_resultado_label_1.setGeometry(QtCore.QRect(0, 20, 800, 40))
        self.tela_resultado_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_resultado_label_1.setObjectName("tela_resultado_label_1")
        self.tela_resultado_textBrowser = QtWidgets.QTextBrowser(self.tela_resultado)
        self.tela_resultado_textBrowser.setGeometry(QtCore.QRect(10, 70, 311, 531))
        self.tela_resultado_textBrowser.setObjectName("tela_resultado_textBrowser")
        self.tela_resultado_label_figura = QtWidgets.QLabel(self.tela_resultado)
        self.tela_resultado_label_figura.setGeometry(QtCore.QRect(330, 75, 450, 470))
        self.tela_resultado_label_figura.setText("")
        self.tela_resultado_label_figura.setPixmap(QtGui.QPixmap(".\\src\\gui\\../A.gif"))
        self.tela_resultado_label_figura.setScaledContents(False)
        self.tela_resultado_label_figura.setObjectName("tela_resultado_label_figura")
        self.tela_resultado_splitter = QtWidgets.QSplitter(self.tela_resultado)
        self.tela_resultado_splitter.setGeometry(QtCore.QRect(330, 560, 461, 40))
        self.tela_resultado_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.tela_resultado_splitter.setObjectName("tela_resultado_splitter")
        #self.tela_resultado_botao_salvar = QtWidgets.QPushButton(self.tela_resultado_splitter)
        #self.tela_resultado_botao_salvar.setObjectName("tela_resultado_botao_salvar")
        self.tela_resultado_botao_voltar = QtWidgets.QPushButton(self.tela_resultado_splitter)
        self.tela_resultado_botao_voltar.setObjectName("tela_resultado_botao_voltar")
        self.stackedWidget.addWidget(self.tela_resultado)
        self.tela_historico = QtWidgets.QWidget()
        self.tela_historico.setObjectName("tela_historico")
        self.tela_historico_label_1 = QtWidgets.QLabel(self.tela_historico)
        self.tela_historico_label_1.setGeometry(QtCore.QRect(0, 20, 800, 40))
        self.tela_historico_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_historico_label_1.setObjectName("tela_historico_label_1")
        self.tela_historico_label_figura = QtWidgets.QLabel(self.tela_historico)
        self.tela_historico_label_figura.setGeometry(QtCore.QRect(330, 64, 450, 481))
        self.tela_historico_label_figura.setText("")
        self.tela_historico_label_figura.setPixmap(QtGui.QPixmap(".\\src\\gui\\../A.gif"))
        self.tela_historico_label_figura.setScaledContents(False)
        self.tela_historico_label_figura.setObjectName("tela_historico_label_figura")
        self.tela_historico_splitter_listas = QtWidgets.QSplitter(self.tela_historico)
        self.tela_historico_splitter_listas.setGeometry(QtCore.QRect(10, 60, 321, 491))
        self.tela_historico_splitter_listas.setOrientation(QtCore.Qt.Vertical)
        self.tela_historico_splitter_listas.setObjectName("tela_historico_splitter_listas")
        self.tela_historico_listWidget = QtWidgets.QListWidget(self.tela_historico_splitter_listas)
        self.tela_historico_listWidget.setAlternatingRowColors(False)
        self.tela_historico_listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.tela_historico_listWidget.setObjectName("tela_historico_listWidget")
        # item = QtWidgets.QListWidgetItem()
        # item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        # item.setCheckState(QtCore.Qt.Unchecked)
        # self.tela_historico_listWidget.addItem(item)
        self.tela_historico_textBrowser = QtWidgets.QTextBrowser(self.tela_historico_splitter_listas)
        self.tela_historico_textBrowser.setObjectName("tela_historico_textBrowser")
        self.tela_historico_splitter_botoes = QtWidgets.QSplitter(self.tela_historico)
        self.tela_historico_splitter_botoes.setGeometry(QtCore.QRect(10, 560, 781, 41))
        self.tela_historico_splitter_botoes.setOrientation(QtCore.Qt.Horizontal)
        self.tela_historico_splitter_botoes.setObjectName("tela_historico_splitter_botoes")
        self.tela_historico_botao_limpar_selecao = QtWidgets.QPushButton(self.tela_historico_splitter_botoes)
        self.tela_historico_botao_limpar_selecao.setObjectName("tela_historico_botao_limpar_selecao")
        self.tela_historico_botao_exportar = QtWidgets.QPushButton(self.tela_historico_splitter_botoes)
        self.tela_historico_botao_exportar.setObjectName("tela_historico_botao_exportar")
        self.tela_historico_botao_importar = QtWidgets.QPushButton(self.tela_historico_splitter_botoes)
        self.tela_historico_botao_importar.setObjectName("tela_historico_botao_importar")
        self.tela_historico_botao_voltar = QtWidgets.QPushButton(self.tela_historico_splitter_botoes)
        self.tela_historico_botao_voltar.setObjectName("tela_historico_botao_voltar")
        self.stackedWidget.addWidget(self.tela_historico)
        self.tela_configs = QtWidgets.QWidget()
        self.tela_configs.setObjectName("tela_configs")
        self.tela_configs_label_1 = QtWidgets.QLabel(self.tela_configs)
        self.tela_configs_label_1.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.tela_configs_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_configs_label_1.setObjectName("tela_configs_label_1")
        self.tela_configs_checkBox = QtWidgets.QCheckBox(self.tela_configs)
        self.tela_configs_checkBox.setGeometry(QtCore.QRect(20, 200, 181, 20))
        self.tela_configs_checkBox.setObjectName("tela_configs_checkBox")
        self.tela_configs_checkBox_2 = QtWidgets.QCheckBox(self.tela_configs)
        self.tela_configs_checkBox_2.setGeometry(QtCore.QRect(20, 240, 181, 20))
        self.tela_configs_checkBox_2.setObjectName("tela_configs_checkBox_2")
        self.tela_configs_checkBox_3 = QtWidgets.QCheckBox(self.tela_configs)
        self.tela_configs_checkBox_3.setGeometry(QtCore.QRect(20, 280, 181, 20))
        self.tela_configs_checkBox_3.setObjectName("tela_configs_checkBox_3")
        self.tela_configs_checkBox_4 = QtWidgets.QCheckBox(self.tela_configs)
        self.tela_configs_checkBox_4.setGeometry(QtCore.QRect(20, 320, 181, 20))
        self.tela_configs_checkBox_4.setObjectName("tela_configs_checkBox_4")
        self.tela_configs_pushButton_18 = QtWidgets.QPushButton(self.tela_configs)
        self.tela_configs_pushButton_18.setGeometry(QtCore.QRect(20, 380, 161, 28))
        self.tela_configs_pushButton_18.setObjectName("tela_configs_pushButton_18")
        self.tela_configs_splitter_rodape = QtWidgets.QSplitter(self.tela_configs)
        self.tela_configs_splitter_rodape.setGeometry(QtCore.QRect(12, 560, 771, 41))
        self.tela_configs_splitter_rodape.setOrientation(QtCore.Qt.Horizontal)
        self.tela_configs_splitter_rodape.setObjectName("tela_configs_splitter_rodape")
        self.tela_configs_botao_salvar = QtWidgets.QPushButton(self.tela_configs_splitter_rodape)
        self.tela_configs_botao_salvar.setObjectName("tela_configs_botao_salvar")
        self.tela_configs_voltar_sem_salvar = QtWidgets.QPushButton(self.tela_configs_splitter_rodape)
        self.tela_configs_voltar_sem_salvar.setObjectName("tela_configs_voltar_sem_salvar")
        self.tela_configs_botao_reset_configs = QtWidgets.QPushButton(self.tela_configs_splitter_rodape)
        self.tela_configs_botao_reset_configs.setObjectName("tela_configs_botao_reset_configs")
        self.tela_configs_splitter_demo = QtWidgets.QSplitter(self.tela_configs)
        self.tela_configs_splitter_demo.setGeometry(QtCore.QRect(17, 110, 761, 28))
        self.tela_configs_splitter_demo.setOrientation(QtCore.Qt.Horizontal)
        self.tela_configs_splitter_demo.setObjectName("tela_configs_splitter_demo")
        self.radioButton = QtWidgets.QRadioButton(self.tela_configs_splitter_demo)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tela_configs_splitter_demo)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tela_configs_splitter_demo)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tela_configs_splitter_demo)
        self.radioButton_4.setObjectName("radioButton_4")
        self.stackedWidget.addWidget(self.tela_configs)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.tela_reco_listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.tela_inicial_botao_reconhecer.clicked.connect(self.mudar_tela_reconhecer)
        self.tela_inicial_botao_historico.clicked.connect(self.mudar_tela_historico)
        self.tela_inicial_botao_config.clicked.connect(self.mudar_tela_config)
        self.tela_inicial_botao_sobre.clicked.connect(self.mudar_tela_sobre)
        self.tela_sobre_botao_voltar.clicked.connect(self.mudar_tela_inicial)
        self.tela_reco_botao_voltar.clicked.connect(self.mudar_tela_inicial)
        self.tela_reco_botao_add_amostra.clicked.connect(self.dialogo_adcionar_amostra)
        self.tela_reco_botao_reconhecer.clicked.connect(self.reconhecer)
        #self.tela_resultado_botao_salvar.clicked.connect(self.salvar_resultado_atual_no_historico)
        self.tela_resultado_botao_voltar.clicked.connect(self.mudar_tela_inicial)
        self.tela_historico_botao_limpar_selecao.clicked.connect(self.limpar_selecao)
        self.tela_historico_botao_exportar.clicked.connect(self.exportar_historico)
        self.tela_historico_botao_importar.clicked.connect(self.importar_historico)
        self.tela_historico_botao_voltar.clicked.connect(self.mudar_tela_inicial)
        self.tela_historico_listWidget.itemSelectionChanged.connect(self.atualizar_tela_historico)
        self.tela_historico_listWidget.itemChanged.connect(self.atualizar_tela_historico)
        self.tela_configs_botao_salvar.clicked.connect(self.salvar_configuracoes)
        self.tela_configs_voltar_sem_salvar.clicked.connect(self.mudar_tela_inicial)
        self.tela_configs_botao_reset_configs.clicked.connect(self.voltar_as_configuracoes_iniciais)
        self.tela_reco_listWidget.itemDoubleClicked.connect(self.remover_amostra)

        # DECLARAR VARS AQUI!
        self.proxima_tela = 0
        self.historico = handler_historico.Historico("historico.json")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CRNN-REM"))
        self.tela_inicial_label_1.setText(_translate("Form", "Classificação de emoções em músicas utilizando aprendizado de máquina"))
        self.tela_inicial_label_2.setText(_translate("Form", "Lucas Lavratti; Rafael B. G. Bueno; Prof. Dr. Alceu S. Britto.\n"
"Escola Politécnica da Pontifícia Universidade Católica do Paraná (PUC-PR)\n"
"Curitiba, 2021"))
        self.tela_inicial_botao_reconhecer.setText(_translate("Form", "Reconhecer"))
        self.tela_inicial_botao_historico.setText(_translate("Form", "Histórico"))
        self.tela_inicial_botao_config.setText(_translate("Form", "Configurações"))
        self.tela_inicial_botao_sobre.setText(_translate("Form", "Sobre"))
        self.tela_sobre_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">What is Lorem Ipsum?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; font-weight:600; color:#000000;\">Lorem Ipsum</span><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Why do we use it?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Where does it come from?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Where can I get some?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</span></p></body></html>"))
        self.tela_sobre_label_1.setText(_translate("Form", "Sobre o projeto"))
        self.tela_sobre_botao_voltar.setText(_translate("Form", "Voltar"))
        self.tela_reco_botao_voltar.setText(_translate("Form", "Voltar"))
        self.tela_reco_label_1.setText(_translate("Form", "Reconhecer"))
        self.tela_reco_botao_add_amostra.setText(_translate("Form", "Adicionar amostra"))
        self.tela_reco_botao_reconhecer.setText(_translate("Form", "Reconhecer"))
        self.tela_reco_label_2.setText(_translate("Form", "TEXTO RECONHECER\nAmostras duplicadas não serão selecionadas\nPara remover uma amostra clique duas vez no item da lista."))
        self.tela_resultado_label_1.setText(_translate("Form", "Resultado"))
        self.tela_resultado_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; background-color:#ffffff;\">Exemplo informações </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getExistingDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrls\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrls</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), and </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getSaveFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p></body></html>"))
        #self.tela_resultado_botao_salvar.setText(_translate("Form", "Salvar no histórico"))
        self.tela_resultado_botao_voltar.setText(_translate("Form", "Voltar"))
        self.tela_historico_label_1.setText(_translate("Form", "Histórico"))
        self.tela_historico_listWidget.setSortingEnabled(False)
        __sortingEnabled = self.tela_historico_listWidget.isSortingEnabled()
        self.tela_historico_listWidget.setSortingEnabled(False)
        #item = self.tela_historico_listWidget.item(0)
        #item.setText(_translate("Form", "ItemExemplo1"))
        self.tela_historico_listWidget.setSortingEnabled(__sortingEnabled)
        self.tela_historico_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; background-color:#ffffff;\">Exemplo informações </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getExistingDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrls\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrls</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), and </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getSaveFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p></body></html>"))
        self.tela_historico_botao_limpar_selecao.setText(_translate("Form", "Limpar Seleção"))
        self.tela_historico_botao_exportar.setText(_translate("Form", "Exportar"))
        self.tela_historico_botao_importar.setText(_translate("Form", "Importar"))
        self.tela_historico_botao_voltar.setText(_translate("Form", "Voltar"))
        self.tela_configs_label_1.setText(_translate("Form", "Configurações"))
        self.tela_configs_checkBox.setText(_translate("Form", "CheckBox"))
        self.tela_configs_checkBox_2.setText(_translate("Form", "CheckBox"))
        self.tela_configs_checkBox_3.setText(_translate("Form", "CheckBox"))
        self.tela_configs_checkBox_4.setText(_translate("Form", "CheckBox"))
        self.tela_configs_pushButton_18.setText(_translate("Form", "PushButton"))
        self.tela_configs_botao_salvar.setText(_translate("Form", "Salvar alterações"))
        self.tela_configs_voltar_sem_salvar.setText(_translate("Form", "Voltar sem salvar"))
        self.tela_configs_botao_reset_configs.setText(_translate("Form", "Voltar as configurações originais"))
        self.radioButton.setText(_translate("Form", "RadioButton"))
        self.radioButton_2.setText(_translate("Form", "RadioButton"))
        self.radioButton_3.setText(_translate("Form", "RadioButton"))
        self.radioButton_4.setText(_translate("Form", "RadioButton"))

    def mudar_tela_reconhecer(self):
        print("UI -> tela reconhecer")
        index = self.stackedWidget.indexOf(self.tela_reco)
        self.stackedWidget.setCurrentIndex(index)

    def mudar_tela_resultado(self):
        print("UI -> tela resultado")
        dict_resultado = self.historico.buscar_ultimo()
        string_formatada = formatar_resultado(dict_resultado)
        self.tela_resultado_textBrowser.setText(string_formatada)
        pixmap = QPixmap(dict_resultado['spectogram'])
        self.tela_resultado_label_figura.setPixmap(pixmap)
        index = self.stackedWidget.indexOf(self.tela_resultado)
        self.stackedWidget.setCurrentIndex(index)

    def mudar_tela_historico(self):
        print("UI -> tela historico")
        index = self.stackedWidget.indexOf(self.tela_historico)
        self.tela_historico_listWidget.clear()
        dict_resultados = self.historico.buscar_historico()
        for key in sorted(dict_resultados, key=int):
            text = "{}  {}".format(key, dict_resultados[key]['arquivo'])
            item = QListWidgetItem(text)
            item.setFlags(item.flags() | QtCore.Qt.ItemIsUserCheckable)
            item.setCheckState(QtCore.Qt.Unchecked)
            self.tela_historico_listWidget.addItem(item)
        self.tela_historico_listWidget.setCurrentRow(0)
        self.atualizar_tela_historico()
        self.stackedWidget.setCurrentIndex(index)

    def atualizar_tela_historico(self):

        # todo: acertar de print para mostrar algo
        checked_items = []
        for index in range(self.tela_historico_listWidget.count()):
            if self.tela_historico_listWidget.item(index).checkState() == Qt.Checked:
                checked_items.append(self.tela_historico_listWidget.item(index).text())
        print(checked_items)
        string_formatada = "[PLACEHOLDER FOR IMG]\n"
        for i in checked_items:
            key = i.split(sep=" ")[0]
            string_formatada += "{}\n".format(key)
        string_formatada += "[PLACEHOLDER FOR IMG]"

        # Texto em baixo da lista
        self.tela_historico_label_figura.setText(string_formatada)
        if not len(self.tela_historico_listWidget.selectedItems()) == 0:
            item = self.tela_historico_listWidget.selectedItems()[0]
            key = item.text().split(sep=" ")[0]
            dict_resultados = self.historico.buscar_historico()
            string_formatada = formatar_resultado(dict_resultados[key])
            self.tela_historico_textBrowser.setText(string_formatada)

    def limpar_selecao(self):
        for index in range(self.tela_historico_listWidget.count()):
            self.tela_historico_listWidget.item(index).setCheckState(QtCore.Qt.Unchecked)

    def mudar_tela_config(self):
        print("UI -> tela config")
        index = self.stackedWidget.indexOf(self.tela_configs)
        self.stackedWidget.setCurrentIndex(index)

    def mudar_tela_sobre(self):
        print("UI -> tela sobre")
        index = self.stackedWidget.indexOf(self.tela_sobre)
        self.stackedWidget.setCurrentIndex(index)

    def mudar_tela_inicial(self):
        print("UI -> tela inicial")
        index = self.stackedWidget.indexOf(self.tela_inicial)
        self.stackedWidget.setCurrentIndex(index)

    def dialogo_adcionar_amostra(self):
        print("UI -> Add amostras")
        file_filter = 'Audio File (*.wav)'
        response = QtWidgets.QFileDialog.getOpenFileNames(
            caption='Select a data file',
            directory=os.path.join(os.getcwd(), os.pardir, os.pardir, 'amostras_exemplo'),
            filter=file_filter,
            initialFilter=file_filter
        )
        for arquivo in response[0]:
            to_remove = []
            for lrow in range(self.tela_reco_listWidget.count()):
                item = self.tela_reco_listWidget.item(lrow)
                if item.text() == arquivo:
                    to_remove.append(lrow)
            for row in to_remove:
                self.tela_reco_listWidget.takeItem(row)
            print("UI -> Amostra  {} adcionada a lista".format(response[0]))
            self.tela_reco_listWidget.addItem(arquivo)

    def remover_amostra(self, item):
        print("UI -> Remover amostra")
        self.tela_reco_listWidget.takeItem(self.tela_reco_listWidget.row(item))
        print("UI -> Amostra  removida")

    def reconhecer(self):
        print("UI -> BACKEND processar_lista(lista de amostras)")

        # Se nada selecionado
        if self.tela_reco_listWidget.count() == 0:
            print("Lista vazia")
            msg = QMessageBox()
            msg.setWindowTitle("CRNN-REM - Erro!")
            msg.setText("A lista está vazia! Selecione pelo menos uma amostra para prosseguir.")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
            print(x)

        # Se tem alguma amostra
        else:

            # Tirar da listWidget  e colocar numa list
            lista_de_amostras = []
            while self.tela_reco_listWidget.count() > 0:
                lista_de_amostras.append(self.tela_reco_listWidget.takeItem(0).text())

            # Processar lista
            self.pop_up = QtWidgets.QWidget()
            self.pop_up_ui = popup_progresso.Ui_Progresso()
            self.pop_up_ui.setupUi(self.pop_up)
            self.pop_up.show()
            self.pop_up.activateWindow()
            self.thread = nosso_back_end.ThreadedProcessarLista(parent=None, amostras=lista_de_amostras, historico=self.historico)
            self.thread.progresso_total.connect(self.pop_up_ui.update_progresso_total)
            self.thread.progresso_parcial.connect(self.pop_up_ui.update_progresso_parcial)
            self.thread.finished.connect(self.finished_rem)
            self.thread.start()

            # Tratamento depende no numero de amostras
            if len(lista_de_amostras) == 1:
                # Se tiver só uma mostra, processa e vai para o resultado
                self.proxima_tela = self.tela_resultado
                print("UI -> RESULTADO")
            else:
                # Se tiver mais que uma mostra, vai para o historico com todos carregados
                self.proxima_tela = self.tela_historico
                print("UI -> HISTORICO")


    def finished_rem(self):
        print('finished_rem')
        if self.proxima_tela == self.tela_resultado:
            self.mudar_tela_resultado()
        elif self.proxima_tela == self.tela_historico:
            self.mudar_tela_historico()
        self.pop_up.close()
        self.pop_up.destroy()

    def exportar_historico(self):
        file_filter = 'JSON File (*.json)'
        response = QtWidgets.QFileDialog.getSaveFileName(
            caption='Select a json file',
            directory=os.path.join(os.getcwd()),
            filter=file_filter,
            initialFilter=file_filter
        )
        if response:
            self.historico.exportar(response[0])

    def importar_historico(self):
        file_filter = 'JSON File (*.json)'
        response = QtWidgets.QFileDialog.getOpenFileName(
            caption='Select a json file',
            directory=os.path.join(os.getcwd()),
            filter=file_filter,
            initialFilter=file_filter
        )
        if response:
            self.historico.importar(response[0])
            self.mudar_tela_historico()

    def salvar_configuracoes(self):
        raise NotImplementedError()

    def voltar_as_configuracoes_iniciais(self):
        raise NotImplementedError()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
