# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui\pop_up_progresso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Progresso(object):
    def setupUi(self, Progresso):
        Progresso.setObjectName("Progresso")
        Progresso.setEnabled(True)
        Progresso.resize(370, 189)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Progresso.sizePolicy().hasHeightForWidth())
        Progresso.setSizePolicy(sizePolicy)
        Progresso.setMinimumSize(QtCore.QSize(370, 189))
        Progresso.setMaximumSize(QtCore.QSize(370, 189))
        self.centralwidget = QtWidgets.QWidget(Progresso)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 351, 171))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label1 = QtWidgets.QLabel(self.splitter)
        self.label1.setMinimumSize(QtCore.QSize(351, 32))
        self.label1.setMaximumSize(QtCore.QSize(351, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.progressBar_total = QtWidgets.QProgressBar(self.splitter)
        self.progressBar_total.setMinimumSize(QtCore.QSize(351, 44))
        self.progressBar_total.setMaximumSize(QtCore.QSize(351, 44))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.progressBar_total.setFont(font)
        self.progressBar_total.setProperty("value", 24)
        self.progressBar_total.setObjectName("progressBar_total")
        self.label2 = QtWidgets.QLabel(self.splitter)
        self.label2.setMinimumSize(QtCore.QSize(351, 32))
        self.label2.setMaximumSize(QtCore.QSize(351, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.progressBar_amostra = QtWidgets.QProgressBar(self.splitter)
        self.progressBar_amostra.setMinimumSize(QtCore.QSize(351, 45))
        self.progressBar_amostra.setMaximumSize(QtCore.QSize(351, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.progressBar_amostra.setFont(font)
        self.progressBar_amostra.setProperty("value", 24)
        self.progressBar_amostra.setObjectName("progressBar_amostra")

        self.retranslateUi(Progresso)
        QtCore.QMetaObject.connectSlotsByName(Progresso)

    def retranslateUi(self, Progresso):
        _translate = QtCore.QCoreApplication.translate
        Progresso.setWindowTitle(_translate("Progresso", "CRNN-REM Progresso"))
        self.label1.setText(_translate("Progresso", "Progresso total"))
        self.label2.setText(_translate("Progresso", "Progresso na amostra"))

    def update_progresso_total(self, progresso_total):
        if 0 <= progresso_total <= 100:
            self.progressBar_total.setValue(progresso_total)

    def update_progresso_parcial(self, progresso_parcial):
        if 0 <= progresso_parcial <= 100:
            self.progressBar_amostra.setValue(progresso_parcial)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Progresso = QtWidgets.QWidget()
    ui = Ui_Progresso()
    ui.setupUi(Progresso)
    Progresso.show()
    sys.exit(app.exec_())
