# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_principal_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets

import src.nosso_back_end as nosso_back_end

class Ui_Form(object):

    def __init__(self):
        self.amostras = []

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 609)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 800, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.tela_inicial = QtWidgets.QWidget()
        self.tela_inicial.setObjectName("tela_inicial")
        self.label = QtWidgets.QLabel(self.tela_inicial)
        self.label.setGeometry(QtCore.QRect(0, 180, 800, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tela_inicial)
        self.label_2.setGeometry(QtCore.QRect(0, 400, 800, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tela_inicial)
        self.label_3.setGeometry(QtCore.QRect(0, 430, 800, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tela_inicial)
        self.label_4.setGeometry(QtCore.QRect(0, 460, 800, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.splitter = QtWidgets.QSplitter(self.tela_inicial)
        self.splitter.setGeometry(QtCore.QRect(100, 300, 600, 50))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.tela_inicial)
        self.tela_sobre = QtWidgets.QWidget()
        self.tela_sobre.setObjectName("tela_sobre")
        self.textBrowser = QtWidgets.QTextBrowser(self.tela_sobre)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 781, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.tela_sobre)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tela_sobre)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.tela_sobre)
        self.tela_reco = QtWidgets.QWidget()
        self.tela_reco.setObjectName("tela_reco")
        self.pushButton_7 = QtWidgets.QPushButton(self.tela_reco)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_6 = QtWidgets.QLabel(self.tela_reco)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.tela_reco)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 191, 41))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.tela_reco)
        self.listWidget.setGeometry(QtCore.QRect(10, 300, 781, 251))
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_8 = QtWidgets.QPushButton(self.tela_reco)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 560, 161, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.splitter_2 = QtWidgets.QSplitter(self.tela_reco)
        self.splitter_2.setGeometry(QtCore.QRect(10, 110, 781, 131))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.splitter_2)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.splitter_2)
        self.label_9.setObjectName("label_9")
        self.label_6.raise_()
        self.pushButton_7.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.listWidget.raise_()
        self.pushButton_8.raise_()
        self.stackedWidget.addWidget(self.tela_reco)
        self.tela_resultado = QtWidgets.QWidget()
        self.tela_resultado.setObjectName("tela_resultado")
        self.label_11 = QtWidgets.QLabel(self.tela_resultado)
        self.label_11.setGeometry(QtCore.QRect(0, 20, 800, 40))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tela_resultado)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 70, 311, 531))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_12 = QtWidgets.QLabel(self.tela_resultado)
        self.label_12.setGeometry(QtCore.QRect(330, 75, 450, 470))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("A.gif"))
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.splitter_3 = QtWidgets.QSplitter(self.tela_resultado)
        self.splitter_3.setGeometry(QtCore.QRect(330, 560, 461, 40))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.stackedWidget.addWidget(self.tela_resultado)
        self.tela_historico = QtWidgets.QWidget()
        self.tela_historico.setObjectName("tela_historico")
        self.label_13 = QtWidgets.QLabel(self.tela_historico)
        self.label_13.setGeometry(QtCore.QRect(0, 20, 800, 40))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tela_historico)
        self.label_14.setGeometry(QtCore.QRect(330, 75, 450, 470))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("A.gif"))
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.splitter_5 = QtWidgets.QSplitter(self.tela_historico)
        self.splitter_5.setGeometry(QtCore.QRect(20, 50, 311, 481))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.listView = QtWidgets.QListView(self.splitter_5)
        self.listView.setObjectName("listView")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.splitter_5)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.splitter_4 = QtWidgets.QSplitter(self.tela_historico)
        self.splitter_4.setGeometry(QtCore.QRect(10, 560, 781, 41))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackedWidget.addWidget(self.tela_historico)
        self.tela_configs = QtWidgets.QWidget()
        self.tela_configs.setObjectName("tela_configs")
        self.label_15 = QtWidgets.QLabel(self.tela_configs)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 771, 41))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.checkBox = QtWidgets.QCheckBox(self.tela_configs)
        self.checkBox.setGeometry(QtCore.QRect(20, 200, 181, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tela_configs)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 240, 181, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tela_configs)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 280, 181, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tela_configs)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 320, 181, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_18 = QtWidgets.QPushButton(self.tela_configs)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 380, 161, 28))
        self.pushButton_18.setObjectName("pushButton_18")
        self.splitter_6 = QtWidgets.QSplitter(self.tela_configs)
        self.splitter_6.setGeometry(QtCore.QRect(12, 560, 771, 41))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.splitter_7 = QtWidgets.QSplitter(self.tela_configs)
        self.splitter_7.setGeometry(QtCore.QRect(17, 110, 761, 28))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.radioButton = QtWidgets.QRadioButton(self.splitter_7)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter_7)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.splitter_7)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.splitter_7)
        self.radioButton_4.setObjectName("radioButton_4")
        self.stackedWidget.addWidget(self.tela_configs)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(self.ir_tela_reconhecer)
        self.pushButton_8.clicked.connect(self.ir_tela_resultado)
        self.pushButton_3.clicked.connect(self.ir_tela_historico)
        self.pushButton_4.clicked.connect(self.ir_tela_config)
        self.pushButton_5.clicked.connect(self.ir_tela_sobre)

        self.pushButton_6.clicked.connect(self.ir_tela_inicial)
        self.pushButton_7.clicked.connect(self.ir_tela_inicial)
        self.pushButton_11.clicked.connect(self.ir_tela_inicial)
        self.pushButton_14.clicked.connect(self.ir_tela_inicial)
        self.pushButton_16.clicked.connect(self.ir_tela_inicial)

        self.pushButton.clicked.connect(self.getFileNames)
        self.listWidget.itemDoubleClicked.connect(self.removeItem)

    def ir_tela_inicial(self):
        self.stackedWidget.setCurrentIndex(0)


    def ir_tela_sobre(self):
        self.stackedWidget.setCurrentIndex(1)


    def ir_tela_reconhecer(self):
        self.stackedWidget.setCurrentIndex(2)


    def ir_tela_resultado(self):
        """
        ANTES DE IR PARA A TELA RESULTADO CALCULA AS COISAS!
        """
        print(self.amostras, len(self.amostras))
        for amostra in self.amostras:
            print(amostra)
            nosso_back_end.gerar_espectograma(amostra[0])

        if len(self.amostras) > 1:
            print("amostras > 1 -> HISTORICO")
            self.stackedWidget.setCurrentIndex(4)
        elif len(self.amostras) == 1:
            print("amostras == 1 -> RESULTADO")
            path = os.path.join('temp', '{}.jpg'.format(os.path.split(
                self.amostras[0][0])[1].split('.')[0]))
            print(path)
            self.label_12.setPixmap(QtGui.QPixmap(path))
            self.stackedWidget.setCurrentIndex(3)


    def ir_tela_historico(self):
        self.stackedWidget.setCurrentIndex(4)


    def ir_tela_config(self):
        self.stackedWidget.setCurrentIndex(5)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CRNN-REM"))
        self.label.setText(_translate("Form", "Classificação de emoções em músicas utilizando aprendizado de máquina"))
        self.label_2.setText(_translate("Form", "Lucas Lavratti; Rafael B. G. Bueno; Prof. Dr. Alceu S. Britto."))
        self.label_3.setText(_translate("Form", "Escola Politécnica da Pontifícia Universidade Católica do Paraná (PUC-PR)"))
        self.label_4.setText(_translate("Form", "Curitiba, 2021"))
        self.pushButton_2.setText(_translate("Form", "Reconhecer"))
        self.pushButton_3.setText(_translate("Form", "Histórico"))
        self.pushButton_4.setText(_translate("Form", "Configurações"))
        self.pushButton_5.setText(_translate("Form", "Sobre"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">What is Lorem Ipsum?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; font-weight:600; color:#000000;\">Lorem Ipsum</span><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Why do we use it?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Where does it come from?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DauphinPlain\'; font-size:x-large; font-weight:600; color:#000000;\">Where can I get some?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:14px; margin-right:29px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:14px; color:#000000;\">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "Sobre o projeto"))
        self.pushButton_6.setText(_translate("Form", "Voltar"))
        self.pushButton_7.setText(_translate("Form", "Voltar"))
        self.label_6.setText(_translate("Form", "Reconhecer"))
        self.pushButton.setText(_translate("Form", "Adicionar amostra"))
        self.pushButton_8.setText(_translate("Form", "Teste -Reconhecer"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "Resultado"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; background-color:#ffffff;\">Exemplo informações </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getExistingDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrls\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrls</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), and </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getSaveFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p></body></html>"))
        self.pushButton_10.setText(_translate("Form", "Salvar no histórico"))
        self.pushButton_11.setText(_translate("Form", "Voltar"))
        self.label_13.setText(_translate("Form", "Histórico"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; background-color:#ffffff;\">Exemplo informações </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span><a name=\"directory\"></a><a href=\"https://doc.qt.io/qt-5/qdir.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#17a81a;\">Dir</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; color:#26282a;\">directory</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<h3 style=\" margin-top:24px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"directoryUrl\"></a><a href=\"https://doc.qt.io/qt-5/qurl.html\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; text-decoration: underline; color:#17a81a;\">Q</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#17a81a;\">Url</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\"> QFileDialog::</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:600; color:#26282a;\">directoryUrl</span><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:large; font-weight:296; color:#26282a;\">() const</span></h3>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">Returns the url of the directory currently being displayed in the dialog.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#setDirectoryUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">setDirectoryUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244; background-color:#ffffff;\">This function was introduced in Qt 5.2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:27px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; font-weight:600; color:#404244;\">See also </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getExistingDirectory</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileUrls\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getOpenFileUrls</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">(), and </span><a href=\"https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileUrl\"><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; text-decoration: underline; color:#17a81a;\">getSaveFileUrl</span></a><span style=\" font-family:\'Titillium Web\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16px; color:#404244;\">().</span></p></body></html>"))
        self.pushButton_9.setText(_translate("Form", "Limpar Dados"))
        self.pushButton_12.setText(_translate("Form", "Exportar"))
        self.pushButton_13.setText(_translate("Form", "Importar"))
        self.pushButton_14.setText(_translate("Form", "Voltar"))
        self.label_15.setText(_translate("Form", "Configurações"))
        self.checkBox.setText(_translate("Form", "CheckBox"))
        self.checkBox_2.setText(_translate("Form", "CheckBox"))
        self.checkBox_3.setText(_translate("Form", "CheckBox"))
        self.checkBox_4.setText(_translate("Form", "CheckBox"))
        self.pushButton_18.setText(_translate("Form", "PushButton"))
        self.pushButton_15.setText(_translate("Form", "Salvar alterações"))
        self.pushButton_16.setText(_translate("Form", "Voltar sem salvar"))
        self.pushButton_17.setText(_translate("Form", "Voltar as configurações originais"))
        self.radioButton.setText(_translate("Form", "RadioButton"))
        self.radioButton_2.setText(_translate("Form", "RadioButton"))
        self.radioButton_3.setText(_translate("Form", "RadioButton"))
        self.radioButton_4.setText(_translate("Form", "RadioButton"))

    def getFileNames(self):
        file_filter = 'Audio File (*.wav)'
        response = QtWidgets.QFileDialog.getOpenFileNames(
            caption='Select a data file',
            directory=os.path.join(os.getcwd(), os.pardir),
            filter=file_filter,
            initialFilter='Excel File (*.xlsx *.xls)'
        )
        self.amostras.append(response[0])
        for row in response[0]:
            self.listWidget.addItem(row)
        return response[0]

    def removeItem(self, item):
        row = self.listWidget.row(item)
        self.amostras.remove(self.amostras[row])
        self.listWidget.takeItem(row)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
